name: june_view_more
description: "expandable view from june_view, include bottom navigation bar, drawer, tap bar, bottom sheet, dialog, snackbar, in app notification, toast etc."
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/june_view_more

version: 1.7.5

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  after_layout:
  device_preview:
  flutter:
    sdk: flutter
  flutter_screenutil:
  flutter_svg:
  gap:
  go_router:
  june:
  june_flow_util:
  styled_widget:
  modal_bottom_sheet: #@add
  bot_toast: #@add
  keyboard_attachable: #@add
  flutter_zoom_drawer: #@add
  beamer: #@add

dev_dependencies:
  bot_toast_module: #@add
  device_preview_module: #@add
  flutter_lints:
  flutter_lints_module: #@add
  flutter_test:
    sdk: flutter
  june_view: #@add
  screenutil_module: #@add

flutter:
  uses-material-design: true