name: june_view_more
description: "JuneFlow Module"
#publish_to: 'none'
#repository: https://github.com/melodysdreamj/juneflow

version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  after_layout: ^1.2.0
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  go_router: ^13.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  june: ^0.8.8
  june_flow_util: ^0.8.19
  styled_widget: ^0.4.1
  modal_bottom_sheet: ^3.0.0 #@add

dev_dependencies:
  device_preview_module: ^0.1.0
  flutter_test:
    sdk: flutter
  hive_module: ^1.0.0+4
  june_view: ^1.4.0+3
  screenutil_module: ^1.0.0+2

flutter:
  uses-material-design: true