name: june_view_more
description: "expandable view from june_view, include bottom navigation bar, drawer, tap bar, bottom sheet, dialog, snackbar, in app notification, toast etc."
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/june_view_more

version: 1.6.2

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  after_layout: ^1.2.0
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  go_router: ^13.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  june: ^0.8.8
  june_flow_util: ^0.8.19
  styled_widget: ^0.4.1
  modal_bottom_sheet: ^3.0.0 #@add
  bot_toast: ^4.1.3 #@add
  keyboard_attachable: ^2.2.0 #@add
  flutter_zoom_drawer: ^3.2.0 #@add

dev_dependencies:
  bot_toast_module: ^0.1.2 #@add
  device_preview_module: ^1.0.0 #@add
  flutter_lints: ^3.0.2
  flutter_lints_module: ^0.0.1+7 #@add
  flutter_test:
    sdk: flutter
  hive_module: ^1.0.1 #@add
  june_view: ^1.6.2 #@add
  screenutil_module: ^1.0.1 #@add

flutter:
  uses-material-design: true